version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
      - pip install boto3
      
  pre_build:
    commands:
      - python pre_build.py
      
  build:
    commands:
      - serverless deploy --stage dev --verbose